/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg60seconds.game;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author nardi.edoardo
 */
public class Interfaccia2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaccia2.class.getName());

    /**
     * Creates new form Interfaccia2
     */
    
public Interfaccia2() {
    setTitle("Scelta Personaggio");
    this.setSize(1000,563);
    initComponents();
    setButtonIcon(jbt_maryjane, "MaryJane.png");
    setButtonIcon(jbt_dolores, "Dolores.png");
    setButtonIcon(jbt_ted, "Ted.png");
    setButtonIcon(jbt_timmy, "Timmy.png");
}

private void setButtonIcon(JButton button, String path) {
    ImageIcon icon = new ImageIcon(path);
    Image img = icon.getImage();

    int width = button.getWidth();
    int height = button.getHeight();

    Image scaledImg = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
    button.setIcon(new ImageIcon(scaledImg));
}
   
                
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jbt_ted = new javax.swing.JButton();
        jbt_dolores = new javax.swing.JButton();
        jbt_timmy = new javax.swing.JButton();
        jbt_maryjane = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 563));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setText("Seleziona il tuo personaggio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 700, -1));

        jbt_ted.setText("jButton5");
        jbt_ted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_tedActionPerformed(evt);
            }
        });
        getContentPane().add(jbt_ted, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 230, 390));

        jbt_dolores.setText("jButton5");
        jbt_dolores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_doloresActionPerformed(evt);
            }
        });
        getContentPane().add(jbt_dolores, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 230, 390));

        jbt_timmy.setText("jButton5");
        jbt_timmy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_timmyActionPerformed(evt);
            }
        });
        getContentPane().add(jbt_timmy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, 390));

        jbt_maryjane.setText("jButton5");
        jbt_maryjane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_maryjaneActionPerformed(evt);
            }
        });
        getContentPane().add(jbt_maryjane, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 230, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_timmyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_timmyActionPerformed
        int m =1;
        this.dispose();
        Interfaccia3 i3 = new Interfaccia3();
        i3.setVisible(true);
    }//GEN-LAST:event_jbt_timmyActionPerformed

    private void jbt_maryjaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_maryjaneActionPerformed
        int m =2;
        this.dispose();
        Interfaccia3 i3 = new Interfaccia3();
        i3.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_maryjaneActionPerformed

    private void jbt_tedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_tedActionPerformed
        int m =3;
        this.dispose();
        Interfaccia3 i3 = new Interfaccia3();
        i3.setVisible(true);  
    }//GEN-LAST:event_jbt_tedActionPerformed

    private void jbt_doloresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_doloresActionPerformed
        int m =4;
        this.dispose();
        Interfaccia3 i3 = new Interfaccia3();
        i3.setVisible(true);          
    }//GEN-LAST:event_jbt_doloresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaccia2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbt_dolores;
    private javax.swing.JButton jbt_maryjane;
    private javax.swing.JButton jbt_ted;
    private javax.swing.JButton jbt_timmy;
    // End of variables declaration//GEN-END:variables
}
